name: Prod Pull Request

on:
  pull_request:
    branches:
      - master
    paths:
      - "prod/**"

defaults:
  run:
    working-directory: prod

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies (Terraform/Terragrunt/kubectl)
      run: |
        brew tap rocketinsights/tgenv
        brew install tfenv tgenv kubectl
        tfenv install
        tgenv install

    - name: Setup infra modules deploy key
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.INFRA_MODULES_DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com

    - name: Terragrunt plan-all
      run: |
        terragrunt plan-all
